import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import '../styles/globals.css'
import NavBar from "../components/NavBar";

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["400", "700"], // Regular and Bold
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={poppins.variable}>
                <NavBar />
                <div>
                    {children}
                </div>
            </body>
        </html>
    );
}